import { useEffect, useState } from 'react';
import type { DirectoryRow } from '../lib/types.js';

/* React-owned highs/lows board. Mounts on #highs-lows-section (highs-lows.html).
   Reads the static assets/highs-lows.json snapshot (generated by
   scripts/gen_highs_lows.py) and lists stocks within 3% of their tracked
   high or low. The window is honest: whatever history the feed has
   accumulated (currently since 18 Sep 2026), labeled on the page. */

interface HlEntry {
  sessions: number;
  start: string;
  end: string;
  high: number;
  low: number;
  close: number;
  off_high_pct: number;
  off_low_pct: number;
}

interface HlDoc {
  as_of: string | null;
  window_start: string | null;
  symbols: Record<string, HlEntry>;
}

function fmtDate(iso: string | null): string {
  if (!iso) return '';
  const m = iso.match(/(\d{4})-(\d{2})-(\d{2})/);
  if (!m) return iso;
  const M = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return Number(m[3]) + ' ' + M[Number(m[2]) - 1] + ' ' + m[1];
}

function money(n: number): string {
  return '₦' + Number(n).toLocaleString('en-NG', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export default function HighsLows(): null {
  const [doc, setDoc] = useState<HlDoc | null>(null);

  useEffect(() => {
    let alive = true;
    fetch('assets/highs-lows.json')
      .then((r) => { if (!r.ok) throw new Error('bad status'); return r.json() as Promise<HlDoc>; })
      .then((d) => { if (alive) setDoc(d); })
      .catch(() => { /* board stays empty with the note */ });
    return () => { alive = false; };
  }, []);

  useEffect(() => {
    if (!doc) return;
    const bySym: Record<string, DirectoryRow> = {};
    (window.directory || []).forEach((e) => { bySym[e.s] = e; });

    const highs: Array<{ s: string; e: HlEntry }> = [];
    const lows: Array<{ s: string; e: HlEntry }> = [];
    Object.keys(doc.symbols).forEach((s) => {
      const e = doc.symbols[s];
      if (e.off_high_pct >= -3) highs.push({ s, e });
      if (e.off_low_pct <= 3) lows.push({ s, e });
    });
    highs.sort((a, b) => b.e.off_high_pct - a.e.off_high_pct);
    lows.sort((a, b) => a.e.off_low_pct - b.e.off_low_pct);

    function rowHtml(s: string, e: HlEntry, pct: number, up: boolean): string {
      const info = bySym[s];
      const name = info ? info.c : s;
      const badge = window.nvBadgeHTML ? window.nvBadgeHTML(s) : '';
      const arrow = up ? '▲' : '▼';
      const cls = up ? 'up' : 'down';
      return '<div class="market-row">' +
        '<button type="button" class="row-main" data-sym="' + s + '" aria-label="' + s + ', ' + name.replace(/"/g, '') + ' — view details">' +
        badge +
        '<span class="row-text"><span class="symbol">' + s + '</span><span class="company">' + name + '</span></span></button>' +
        '<div class="price">' + money(e.close) + '</div>' +
        '<div class="move ' + cls + '">' + arrow + ' ' + Math.abs(pct).toFixed(2) + '% ' + (up ? 'off high' : 'off low') + '</div></div>';
    }

    const highsEl = document.getElementById('hlHighs');
    const lowsEl = document.getElementById('hlLows');
    if (highsEl) {
      highsEl.innerHTML = highs.length
        ? highs.map(({ s, e }) => rowHtml(s, e, e.off_high_pct, true)).join('')
        : '<div class="empty-note">No stocks within 3% of their tracked high.</div>';
    }
    if (lowsEl) {
      lowsEl.innerHTML = lows.length
        ? lows.map(({ s, e }) => rowHtml(s, e, e.off_low_pct, false)).join('')
        : '<div class="empty-note">No stocks within 3% of their tracked low.</div>';
    }

    /* row clicks open the stock modal */
    function onClick(ev: Event) {
      const b = (ev.target as HTMLElement).closest('[data-sym]') as HTMLElement | null;
      if (!b) return;
      const s = b.getAttribute('data-sym') || '';
      if (window.nvOpenModal) window.nvOpenModal(s, b);
      else window.location.href = 'stocks/' + s + '.html';
    }
    const section = document.getElementById('highs-lows-section');
    if (section) section.addEventListener('click', onClick);

    const lede = document.getElementById('hlLede');
    if (lede) lede.textContent = 'Stocks trading at or near the top and bottom of their tracked range (' + fmtDate(doc.window_start) + ' – ' + fmtDate(doc.as_of) + ').';
    const note = document.getElementById('hlNote');
    if (note) note.textContent = 'Range is built from Nairaview\u2019s tracked daily closes and grows as history accumulates — not a full 52-week window yet. Data as of ' + fmtDate(doc.as_of) + '.';

    return () => { if (section) section.removeEventListener('click', onClick); };
  }, [doc]);

  return null;
}
