#!/usr/bin/env python3
"""Download per-ticker company icons from ngnmarket, convert to PNG,
and write assets/logos.js manifest. Reads tickers from /tmp/iconcheck.txt
(lines: TICKER CODE SIZE), keeps CODE==200 and SIZE>500."""
import os, sys, json, subprocess
from PIL import Image

CHECK = '/tmp/iconcheck.txt'
OUTDIR = os.path.expanduser('~/workspace/nairaview/assets/logos')
os.makedirs(OUTDIR, exist_ok=True)

def fetch(ticker):
    url = f'https://ngnmarket.com/icons/companies/{ticker}.ico'
    p = subprocess.run(['curl', '-s', '--max-time', '25', '-L', url],
                       capture_output=True)
    return p.stdout

def save_png(ticker, data):
    tmp = f'/tmp/logo_{ticker}.ico'
    with open(tmp, 'wb') as f:
        f.write(data)
    try:
        im = Image.open(tmp)
        # largest frame
        if getattr(im, 'n_frames', 1) > 1:
            best, bestpx = 0, 0
            for i in range(im.n_frames):
                im.seek(i)
                px = im.size[0] * im.size[1]
                if px > bestpx:
                    best, bestpx = i, px
            im.seek(best)
        im = im.convert('RGBA')
        # downscale if huge
        if max(im.size) > 256:
            im.thumbnail((256, 256), Image.LANCZOS)
        out = os.path.join(OUTDIR, f'{ticker}.png')
        im.save(out, 'PNG')
        return os.path.getsize(out)
    except Exception as e:
        print(f'{ticker}: convert failed: {e}', file=sys.stderr)
        return 0
    finally:
        try:
            os.remove(tmp)
        except OSError:
            pass

manifest = {}
with open(CHECK) as f:
    for line in f:
        parts = line.split()
        if len(parts) < 3:
            continue
        ticker, code, size = parts[0], parts[1], int(parts[2])
        if code != '200' or size <= 500:
            continue
        data = fetch(ticker)
        if len(data) < 500:
            print(f'{ticker}: download too small ({len(data)}b), skipping')
            continue
        # sanity: must look like an image
        if data[:4] not in (b'\x00\x00\x01\x00', b'\x89PNG', b'GIF8', b'\xff\xd8\xff\xe0', b'RIFF'):
            print(f'{ticker}: not an image (magic {data[:4]!r}), skipping')
            continue
        outsize = save_png(ticker, data)
        if outsize > 0:
            manifest[ticker] = True
            print(f'{ticker}: ok ({outsize}b png)')
        else:
            print(f'{ticker}: FAILED')

js = '// Auto-generated by scripts/fetch_logos.py — tickers with a self-hosted logo.\n'
js += 'window.NV_LOGOS = ' + json.dumps(manifest, sort_keys=True) + ';\n'
with open(os.path.expanduser('~/workspace/nairaview/assets/logos.js'), 'w') as f:
    f.write(js)
print(f'\nmanifest: {len(manifest)} logos -> assets/logos.js')
